eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080

spring:
  application:
    name: api-gateway


  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8082/
          predicates:
            - Path=/authentication/**
        - id: booking-service
          uri: http://localhost:8084/
          predicates:
            - Path=/bookings/**
        - id: location-service
          uri: http://localhost:8088/
          predicates:
            - Path=/location/**
        - id: content-search-service
          uri: http://localhost:8086/
          predicates:
            - Path=/flat/**, /pg/**, /hostel/**
        - id: owner-chat-service
          uri: http://localhost:8092/
          predicates:
            - Path=/ownerchat/1/**
        - id: user-owner-service
          uri: http://localhost:8098/
          predicates:
            - Path=/user/**
        - id: property-service
          uri: http://localhost:8096/
          predicates:
            - Path=/api/**
        - id: payment-service
          uri: http://localhost:8094/
          predicates:
            - Path=/rentalhome/**


